# Use the Miniconda image
FROM continuumio/miniconda3

RUN apt-get update \
  && apt-get install -y build-essential \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Copy all files
COPY . .

# Create the environment:
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "pubkb", "/bin/bash", "-c"]

# Install the dependencies specified in the requirements file
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8501

# Command to run the application
ENTRYPOINT ["/opt/conda/envs/pubkb/bin/streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]